- name: Condition Demo
  hosts: iosxe1*
  # hosts: iosxe1*,junos1*
  gather_facts: true
  vars:
    mynic: GigabitEthernet1
  vars_files:
    - vars/outside_vars.yml
  tasks:
    - name: Block of Cisco Tasks
      block:
        - name: Collect Facts Yourself
          cisco.ios.ios_facts:
            gather_subset: all

        - name:  Print the facts
          ansible.builtin.copy:
            dest: ./iosxe1_facts.txt
            content: |
              API         = "{{ ansible_net_api }}"
              Hostname    = "{{ ansible_facts['net_hostname'] }}"
              Image       = "{{ ansible_facts['net_image'] }}"
              Serial Num  = "{{ ansible_facts['net_serialnum'] }}"
              Version     = "{{ ansible_facts['net_version'] }}"
              System      = "{{ ansible_facts['net_system'] }}"
              Model       = "{{ ansible_facts['net_model'] }}"

        - name: Setup Login Banner
          cisco.ios.ios_banner:
            banner: login
            text: "{{ inventory_hostname }} -- {{ ansible_facts['net_serialnum'] }}"
            state: present
      when:
        - ansible_network_os == "cisco.ios.ios"
        - ansible_facts['net_version'] > "18" or ansible_net_api == "cliconf"
        - meme is not defined
        - mynic in simple_nics_list
      # when: ansible_network_os == "cisco.ios.ios" and  ansible_facts['net_version'] > "18"
    
    # - name: Block of Juniper Tasks
    #   block:
    #     - name: Open 830 port for netconf
    #       vars:
    #         ansible_connection: ansible.netcommon.network_cli
    #       junipernetworks.junos.junos_netconf:
    #         netconf_port: 830
    #         state: present
 
    #     - name: Backup Junos configurations
    #       junipernetworks.junos.junos_config:
    #         backup: true
    #         backup_options:
    #           dir_path: ./data/
    #           filename: "{{ inventory_hostname }}.txt"
 
    #     - name: Close 830 port for netconf
    #       junipernetworks.junos.junos_netconf:
    #         netconf_port: 830
    #         state: absent
    #       vars:
    #         ansible_connection: ansible.netcommon.network_cli
    #   when: ansible_network_os == "junipernetworks.junos.junos"
