- name: failed_when/fail/assert Demo
  hosts: iosxe1*
  gather_facts: false
  tasks:
    - name: Collect Facts Yourself
      cisco.ios.ios_facts:
        gather_subset: all

    # - name:  Print the facts
    #   ansible.builtin.copy:
    #     dest: ./iosxe1_facts.txt
    #     content: |
    #       API         = "{{ ansible_facts['net_api'] }}"
    #       Image       = "{{ ansible_facts['net_image'] }}"
    #       Serial Num  = "{{ ansible_facts['net_serialnum'] }}"
    #       Version     = "{{ ansible_facts['net_version'] }}"
    #       Model       = "{{ ansible_facts['net_model'] }}"
    #       Memory Free = "{{ansible_facts['net_memfree_mb'] }}"
    #       Memory Total = "{{ansible_facts['net_memtotal_mb'] }}"

    - name: Change Description Config
      cisco.ios.ios_interfaces:
        config:
          - name: GigabitEthernet1
            description: "Hello Day 4"
        state: merged
      # failed_when: not output.changed 
      register: output

    # - name: Print
    #   ansible.builtin.debug:
    #     msg: "{{ output }}"


    # - name: Fail Playbook via fail Module
    #   ansible.builtin.fail:
    #     msg: "Previous task output not according to my expectation"
    #   when: not output.changed 

    - name: Faili/Pass Playbook via assert Module
      ansible.builtin.assert:
        fail_msg: "Previous task output NOT GOOD"
        success_msg: "Fantastic"
        that:
          - output.changed 
          - ansible_facts['net_system'] == "ios"

    - name: Setup Login Banner
      cisco.ios.ios_banner:
        banner: login
        text: "{{ inventory_hostname }} -- {{ ansible_facts['net_serialnum'] }} -- {{ ansible_facts['net_model'] }}"
        state: present
      when: ansible_facts['net_version'] > "17"
