- name: Handlers Demo
  hosts: iosxe1*
  gather_facts: false
  tasks:
    - name: Change Description Config
      cisco.ios.ios_interfaces:
        config:
          - name: GigabitEthernet1
            description: "Hello Day 2"
        state: merged
      notify:
        - Changed the Description
        - Save Config of Device

    - name: Setup Login Banner
      cisco.ios.ios_banner:
        banner: login
        text: "Day 2 LOGIN Banners"
        state: present
      notify:
        - Changed the BANNER
        - Save Config of Device

  handlers:
    # Dependency Tasks called by tasks section
    # Handlers runs in orderthey are defined not notified
    # Handler will run only once doesn't matter how many times invoked

    - name: WASTED HANDLER
      ansible.builtin.debug:
        msg: "WHY ARE EVEN THERE"

    - name: Changed the BANNER
      ansible.builtin.debug:
        msg: "YES changed LOGIN BANNER"

    - name: Save Config of Device
      cisco.ios.ios_config:
        save_when: always

    - name: Changed the Description
      ansible.builtin.debug:
        msg: "YES i changed DESC"
