- name: Loops Demo
  hosts: iosxe1*
  gather_facts: false
  vars_files:
    - vars/outside_vars.yml

  tasks:
    - name: Print Simple List
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{ simple_nics_list }}"

    - name: Print Complex List
      ansible.builtin.debug:
        msg: "{{ item.name }} -- {{ item['desc'] }}"
      loop: "{{ complex_nics_list }}"

    # Loop only accept List/Array
    # Convert Dict into List
    - name: Print Dictionary
      ansible.builtin.debug:
        msg: "{{ item.key }} ++ {{ item['value'] }}"
      loop: "{{ nics_dict | dict2items }}"

    - name: Ping few Systems
      cisco.ios.ios_ping:
        dest: "{{ item }}"
      loop:
        - iosxe1.lab.example.com
        - iosxe2.lab.example.com
      register: zhenya_out

    # - name: Print the Captured Output
    #   ansible.builtin.debug:
    #     msg: "{{ zhenya_out.results }}"
        # msg: "{{ zhenya_out }}"
        #
    - name: Loop the Captured Output
      ansible.builtin.debug:
        msg: "{{ item['commands'] }} -- {{ item['item'] }} -- {{ item['packets_rx'] }}"
      loop: "{{ zhenya_out.results }}"



